### ISSUE TITLE
unsynchronized access to hosts.Cfg?

### ISSUE THREAD

**Issue by davidbirdsong** [cznic/dns#4]
https://github.com/cznic/dns/blob/master/hosts/hosts.go#L87

I presume a resolver.Resolver is intended to be safe to access from multiple goroutines.

Here's the race detector complaining:
```bash
WARNING: DATA RACE
Read by goroutine 21:
  github.com/cznic/dns/hosts.(*Cfg).File()
      /home/david/src/golang/src/github.com/cznic/dns/hosts/hosts.go:87 +0x9c
  github.com/cznic/dns/resolver.New.func2()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:202 +0xf8
  github.com/cznic/dns/resolver.(*Resolver).Lookup()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:507 +0x6c0
  github.com/zebrafishlabs/hwyman/server.newTransport.func1()
      /home/david/src/golang/src/github.com/zebrafishlabs/hwyman/server/transport.go:54 +0x319
  net/http.(*Transport).dial()
      /tmp/workdir/go/src/net/http/transport.go:499 +0xd1
  net/http.(*Transport).dialConn()
      /tmp/workdir/go/src/net/http/transport.go:596 +0x237a
  net/http.(*Transport).getConn.func4()
      /tmp/workdir/go/src/net/http/transport.go:549 +0x73

Previous write by goroutine 20:
  github.com/cznic/dns/hosts.(*Cfg).File()
      /home/david/src/golang/src/github.com/cznic/dns/hosts/hosts.go:87 +0xe3
  github.com/cznic/dns/resolver.New.func2()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:202 +0xf8
  github.com/cznic/dns/resolver.(*Resolver).sbelt()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:348 +0x6b
  github.com/cznic/dns/resolver.(*Resolver).Lookup()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:593 +0xbe4
  github.com/zebrafishlabs/hwyman/server.newTransport.func1()
      /home/david/src/golang/src/github.com/zebrafishlabs/hwyman/server/transport.go:54 +0x319
  net/http.(*Transport).dial()
      /tmp/workdir/go/src/net/http/transport.go:499 +0xd1
  net/http.(*Transport).dialConn()
      /tmp/workdir/go/src/net/http/transport.go:596 +0x237a
  net/http.(*Transport).getConn.func4()
      /tmp/workdir/go/src/net/http/transport.go:549 +0x73
```

**Comment by davidbirdsong** [comment]
I realized I was passing in an empty temp fille to `resolver.New`, but still might be helpful to either fail to return a resolver.Resolver or some other action to avoid the race condition that repeated calls to `*hosts.Cfg.File()` can cause.

**Comment by cznic** [comment]
From a quick look into this it seems that no methods involved in the race are documented to be safe for concurrent access from multiple goroutines. However, some of them probably should be made safe for such use.

Let me please ask you to suggest which things to make concurrent safe and I'll change the API. I think the added safety is a backwards compatible change.

Be aware, that `(*Resolver).Lookup`, for example, is problematic. Due to network traffic problems, it can can run for several seconds before returning. It can be guarded by a mutex, but would you be comfortable with that?

So it might be necessary to run a (central) instance of `Resolver` in a separate goroutine and communicate with that 'kernel' through channels where the cached results return immediately and the non-cached results are obtained in a serialization-of-requests way. It can be done in client code, it can be done in the `resolver` package. What's you opinion?

**Comment by davidbirdsong** [comment]
> Be aware, that (*Resolver).Lookup, for example, is problematic. Due to network traffic problems, it can run for several seconds before returning. It can be guarded by a mutex, but would you be comfortable with that?

Is there no way to run parallel Lookups? I'm writing a forward http proxy and so any requests that cause a name resolution that hits a slow or mis-behaving DNS server could block and slow unrelated requests needing name resolution (not in cache.)


> So it might be necessary to run a (central) instance of Resolver in a separate goroutine and communicate with that 'kernel' through channels where the cached results return immediately and the non-cached results are obtained in a serialization-of-requests way. It can be done in client code, it can be done in the resolver package. What's you opinion?

So far I've only interacted via `(*Resolver).Lookup` which I understood to manage the cache entries on my behalf. If `Lookup` can block, wouldn't cached results get blocked behind a slow network request if I went the route of the 'kernel' goroutine that runs the central Resolver?

**Comment by cznic** [comment]
The serialization/blocking would apply only to requests not found in the cache.

I have an idea which is ugly, but it might be what you would like: Whenever a query has to be sent to a server, `Resolver` can internally make a safe clone of itself and perform the blocking operation in that clone, while all of those instances would, of course, share the same DNS cache, which seems to be already concurrent access safe. The size of the resolver instance is smallish (6 words), so it would not make too much garbage(*), but `Resolver` would now completely support parallel `Lookup`s without serializing the network requests in `Resolver` - only at much lower network layers.

What do you think?

*: And we can use `sync.Pool` to the rescue.

**Comment by davidbirdsong** [comment]
This sounds great. 

If I had to guess, is the ugly part going to leverage `unsafe.Pointer` and `atomic.LoadPointer` and `atomic.StorePointer`?

**Comment by cznic** [comment]
The ugly thing is that it solves a design flaw in an inelegant, yet somewhat simple way. I should have considered parallelism of `Lookup` right from the beginning.

**Comment by cznic** [comment]
It's an old library and I forgot most of it. Turns out that the resolver was prepared for parallel tasks already. I fixed concurrent access to `hosts.Cfg`. Please checkout branch `issue4`, test and let me know the results. If the patch fixes your problem I'll then merge it to `master`. Thanks.

**Comment by davidbirdsong** [comment]
`hosts.Cfg` not warning anymore, but `resolv.(*Cfg).Conf()` remains a sync problem.

```
WARNING: DATA RACE
Read by goroutine 115:
  github.com/cznic/dns/resolv.(*Cfg).Conf()
      /home/david/src/golang/src/github.com/cznic/dns/resolv/resolv.go:100 +0x9c
  github.com/cznic/dns/resolver.New.func2()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:213 +0x46c
  github.com/cznic/dns/resolver.(*Resolver).Lookup()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:507 +0x6c0
  github.com/cznic/dns/resolver.(*Resolver).needNSAdr.func1()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:384 +0x22d

Previous write by goroutine 22:
  github.com/cznic/dns/resolv.(*Cfg).Conf()
      /home/david/src/golang/src/github.com/cznic/dns/resolv/resolv.go:100 +0xe3
  github.com/cznic/dns/resolver.New.func2()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:213 +0x46c
  github.com/cznic/dns/resolver.(*Resolver).sbelt()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:348 +0x6b
  github.com/cznic/dns/resolver.(*Resolver).Lookup()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:593 +0xbe4
  github.com/cznic/dns/resolver.(*Resolver).needNSAdr.func1()
      /home/david/src/golang/src/github.com/cznic/dns/resolver/resolver.go:384 +0x22d
```

I know this thread was about `hosts`, so let me know if you want it as a separate issue.

**Comment by cznic** [comment]
> I know this thread was about hosts, so let me know if you want it as a separate issue.

No problem. Will look into it. Thanks for your reports!

**Comment by cznic** [comment]
@davidbirdsong Please try the second patch and let me know the outcome. Thank you.

**Comment by davidbirdsong** [comment]
I've run the second patch for 2 days now with no data race warnings. Looks good.

**Comment by cznic** [comment]
@davidbirdsong Thanks for testing this. Merged into master.
